import sharp from 'sharp';
import { readdirSync, readFileSync } from 'fs';
import { join, extname } from 'path';

// LinkedIn optimal cover image size
const IMAGE_WIDTH = 1200;
const IMAGE_HEIGHT = 627;

/**
 * Pick a random source file from the project
 * @param {string} projectPath - Root directory of the project
 * @returns {Object} { filename, content }
 */
export function pickRandomSourceFile(projectPath) {
  const srcDir = join(projectPath, 'src');
  
  try {
    const files = readdirSync(srcDir)
      .filter(f => ['.js', '.ts', '.jsx', '.tsx'].includes(extname(f)))
      .map(f => join(srcDir, f));
    
    if (files.length === 0) {
      return null;
    }

    const randomFile = files[Math.floor(Math.random() * files.length)];
    const content = readFileSync(randomFile, 'utf8');
    
    return {
      filename: randomFile.split('/').pop(),
      content: content.split('\n').slice(0, 8).join('\n'), // First 8 lines
    };
  } catch (error) {
    return null;
  }
}

/**
 * Generate SVG with blurred code background and text overlay
 * @param {string} headline - Headline text
 * @param {string} author - Author name
 * @param {string} codeSnippet - Code snippet for background
 * @returns {string} SVG markup
 */
function createCoverSvg(headline, author, codeSnippet = '') {
  const escapeXml = (str) => {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  };

  const headlineText = escapeXml(headline);
  const authorText = escapeXml(author);
  const codeText = escapeXml(codeSnippet.substring(0, 200)); // Limit code length

  return `
    <svg width="${IMAGE_WIDTH}" height="${IMAGE_HEIGHT}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <!-- Gradient background -->
        <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#0f172a;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#1a1f35;stop-opacity:1" />
        </linearGradient>
        
        <!-- Blur filter for code -->
        <filter id="codeBlur">
          <feGaussianBlur in="SourceGraphic" stdDeviation="3" />
        </filter>
        
        <!-- Dark overlay -->
        <linearGradient id="overlay" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color:#000000;stop-opacity:0.7" />
          <stop offset="100%" style="stop-color:#000000;stop-opacity:0.5" />
        </linearGradient>
      </defs>
      
      <!-- Background -->
      <rect width="${IMAGE_WIDTH}" height="${IMAGE_HEIGHT}" fill="url(#bg)" />
      
      <!-- Blurred code background (if available) -->
      <g filter="url(#codeBlur)" opacity="0.15">
        <text x="50" y="100" font-family="Monaco, monospace" font-size="16" fill="#10b981">
          <tspan x="50">${codeText.split('\n').slice(0, 3).join('\\n')}</tspan>
        </text>
      </g>
      
      <!-- Dark overlay for readability -->
      <rect width="${IMAGE_WIDTH}" height="${IMAGE_HEIGHT}" fill="url(#overlay)" />
      
      <!-- Left accent bar -->
      <rect x="0" y="0" width="6" height="${IMAGE_HEIGHT}" fill="#10b981" />
      
      <!-- Headline - positioned to avoid cutoff -->
      <text x="60" y="240" font-family="system-ui, -apple-system, sans-serif" font-size="52" font-weight="700" fill="#ffffff">
        <tspan x="60" dy="0">${headlineText.substring(0, 40)}</tspan>
        ${headlineText.length > 40 ? `<tspan x="60" dy="65">${headlineText.substring(40, 80)}</tspan>` : ''}
      </text>
      
      <!-- Author attribution -->
      <text x="60" y="550" font-family="system-ui, -apple-system, sans-serif" font-size="20" fill="#94a3b8">
        — ${authorText}
      </text>
      
      <!-- Small "by gitpost" label -->
      <text x="${IMAGE_WIDTH - 200}" y="40" font-family="Monaco, monospace" font-size="13" fill="#10b98166">
        Generated by gitpost
      </text>
    </svg>
  `;
}

/**
 * Generate a cover image for the LinkedIn post
 * @param {Object} options
 * @param {string} options.headline - Post headline
 * @param {string} options.author - Author name
 * @param {string} options.outputPath - Where to save the image
 * @param {string} options.projectPath - Project root (for picking source file)
 * @returns {Promise<string>} Path to the generated image
 */
export async function generateCoverImage({
  headline = 'What I shipped this week',
  author = 'Developer',
  outputPath = './gitpost-cover.png',
  projectPath = process.cwd(),
} = {}) {
  try {
    // Try to get a code snippet from the project
    let codeSnippet = '';
    const sourceFile = pickRandomSourceFile(projectPath);
    if (sourceFile) {
      codeSnippet = sourceFile.content;
    }

    // Create the SVG with code background
    const svgString = createCoverSvg(headline, author, codeSnippet);

    // Convert SVG to PNG using sharp
    const buffer = await sharp(Buffer.from(svgString), {
      density: 150,
    })
      .png()
      .toBuffer();

    // Save the final image
    await sharp(buffer)
      .resize(IMAGE_WIDTH, IMAGE_HEIGHT, {
        fit: 'contain',
        background: { r: 15, g: 23, b: 42, alpha: 1 },
      })
      .png()
      .toFile(outputPath);

    return outputPath;
  } catch (error) {
    throw new Error(`Failed to generate cover image: ${error.message}`);
  }
}

/**
 * Format headline for image (limit length for readability)
 * @param {string} headline - Raw headline
 * @returns {string} Formatted headline
 */
export function formatHeadlineForImage(headline) {
  // Limit to ~80 chars (can wrap to 2 lines in new layout)
  if (headline.length > 80) {
    return headline.substring(0, 77) + '...';
  }
  return headline;
}
